blank_issues_enabled: false
contact_links:
  - name: Integration Support
    url: https://flutterwave.com/ng/support/submit-request
    about: If you need any help using this package, contact our support team.
