blank_issues_enabled: false
contact_links:
  - name: Integration Support
    url: https://flutterwave.com/ng/support/submit-request
    about: For help with this package, contact our support team and select "Integrations" in the support form.
